package com.px.picturebackend.api.aliyunai.model;

import cn.hutool.core.annotation.Alias;
import lombok.Data;

import java.io.Serializable;

/**
 * packageName: com.px.picturebackend.api.aliyunai.model
 *
 * @author: idpeng
 * @version: 1.0
 * @className: CreateOutPaintingTaskRequest
 * @date: 2025/8/24 16:14
 * @description: 扩图任务请求类
 */
@Data
public class CreateOutPaintingTaskRequest implements Serializable {

    /**
     * 模型名称，使用图像编辑模型wanx2.1-imageedit
     */
    private String model = "wanx2.1-imageedit";

    /**
     * 输入图像信息
     */
    private Input input;

    /**
     * 图像处理参数
     */
    private Parameters parameters;

    @Data
    public static class Input {
        /**
         * 必选，功能类型，扩图功能设置为expand
         */
        private String function = "expand";
        
        /**
         * 可选，提示词，描述扩图内容
         */
        private String prompt;
        
        /**
         * 必选，基础图像URL
         */
        @Alias("base_image_url")
        private String baseImageUrl;
    }

    @Data
    public static class Parameters implements Serializable {
        /**
         * 可选，上方扩图比例，默认值1.0，范围为[1.0, 3.0]
         */
        @Alias("top_scale")
        private Float topScale = 1.0f;

        /**
         * 可选，下方扩图比例，默认值1.0，范围为[1.0, 3.0]
         */
        @Alias("bottom_scale")
        private Float bottomScale = 1.0f;

        /**
         * 可选，左侧扩图比例，默认值1.0，范围为[1.0, 3.0]
         */
        @Alias("left_scale")
        private Float leftScale = 1.0f;

        /**
         * 可选，右侧扩图比例，默认值1.0，范围为[1.0, 3.0]
         */
        @Alias("right_scale")
        private Float rightScale = 1.0f;

        /**
         * 可选，生成图像数量，默认值1，范围为[1, 4]
         */
        private Integer n = 1;

        /**
         * 可选，随机种子，用于控制生成结果的随机程度，默认值为当前时间戳
         */
        private Long seed;

        /**
         * 可选，输出图像的宽高比，默认空字符串，不设置宽高比
         * 可选值：["", "1:1", "3:4", "4:3", "9:16", "16:9"]
         */
        @Alias("output_ratio")
        private String outputRatio;

        /**
         * 可选，开启图像最佳质量模式，默认值为false  
         * 若为 true，耗时会成倍增加，建议仅在对图像质量有较高要求时使用
         */
        @Alias("best_quality")
        private Boolean bestQuality = false;

        /**
         * 可选，限制模型生成的图像文件大小，默认值为true
         * - 单边长度 <= 10000：输出图像文件大小限制为 5MB 以下
         * - 单边长度 > 10000：输出图像文件大小限制为 10MB 以下
         */
        @Alias("limit_image_size")
        private Boolean limitImageSize = true;

        /**
         * 可选，添加 "Generated by AI" 水印，默认值为false
         */
        @Alias("add_watermark")
        private Boolean addWatermark = false;
    }
}

