# 环境变量配置示例
# 请复制此文件为 application-local.yml 并填入真实的配置值
# 注意：不要将包含真实密钥的配置文件提交到版本控制系统

# 阿里云AI配置
aliYunAi:
  apiKey: your-ali-yun-ai-api-key-here

# 腾讯云COS配置
cos:
  client:
    host: https://picture-1356335042.cos.ap-chongqing.myqcloud.com
    secretId: your-tencent-cos-secret-id-here
    secretKey: your-tencent-cos-secret-key-here
    region: ap-chongqing
    bucket: picture-1356335042
    # 分块上传配置（可选，有默认值）
    multipartUploadThreshold: 10485760  # 10MB，文件大小超过此值时使用分块上传
    partSize: 2097152                   # 2MB，每个分块的大小
    threadPoolSize: 5                   # 线程池大小，用于并发上传分块

# 环境变量设置说明：
# 1. 在开发环境中，可以创建 application-local.yml 文件
# 2. 在生产环境中，建议使用系统环境变量：
#    - ALI_YUN_AI_API_KEY=your-actual-api-key
#    - TENCENT_COS_SECRET_ID=your-actual-secret-id
#    - TENCENT_COS_SECRET_KEY=your-actual-secret-key